feat(template-mpi): agrega demo para maquetados
andes/plex pull request #203
Opened 2020-07-31 12:24 UTC by JSantarelli

Se agrega maquetado realizado para MPI actualizado y se crea página de inicio para los templates; que direcciona a maquetados según tipologías (por ahora sólo 'listado-detalle') o módulos (por ahora sólo MPI).

![plex-templates](https://user-images.githubusercontent.com/5895886/89034444-54dd9780-d30f-11ea-83f0-9b3e9e422abf.png)

2020-07-31 14:54 UTC, andrrrl commented on src/demo/app/templates/listado-sidebar/listado-sidebar.html
> +            <plex-help type="help" titulo="Ayuda de este panel" size="md" title="este es un atributo [title]"
Hay algo con el contenido del plex-help porque no se ve :thinking:

2020-07-31 14:58 UTC, andrrrl commented on src/demo/app/templates/template-inicio.ts
> +        private plex: Plex,
No hace falta traer Plex si no se usa :sweat_smile:

2020-07-31 15:01 UTC, JSantarelli commented on src/demo/app/templates/listado-sidebar/listado-sidebar.html
> +            <plex-help type="help" titulo="Ayuda de este panel" size="md" title="este es un atributo [title]"
Gracias Andrews, tenía un selector 'info' el panel desplegable. Cambié el type y funcionó. De paso mandé el plex-help al final (como dice el lineamiento no?)

2020-07-31 15:04 UTC, JSantarelli commented on src/demo/app/templates/template-inicio.ts
> +        private plex: Plex,
ups! Eliminado.

2020-09-11 13:42 UTC, liquid36 commented
Hice el rebase, hay algunos iconos que no se ven. Cuando puedan los revisan y así ya le damos salida a esto. Después faltaría agregar algunas fotos de applitools que para eso estamos incorporando esto acá.

2020-09-30 14:43 UTC, andrrrl requested changes

2020-09-30 14:43 UTC, andrrrl commented on src/demo/app/templates/listado-sidebar/listado-sidebar.html
> +            <plex-help type="info" titulo="Ayuda de este panel" size="md" title="este es un atributo [title]"
No se usa más title="" para evitar tooltips repetidos, ahora sólo usamos tooltip=""
```suggestion
            <plex-help type="info" titulo="Ayuda de este panel" size="md" tooltip="este es un atributo [title]"
```

2020-09-30 16:01 UTC, andrrrl approved these changes
:partying_face:

2020-09-30 16:06 UTC, merged

2020-10-01 13:16 UTC, liquid36 commented
:tada: This PR is included in version 7.1.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@andes/plex/v/7.1.0)
- [GitHub release](https://github.com/andes/plex/releases/tag/v7.1.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: