feat(plex-card): envolvente rectangular de badge, label, button
andes/plex pull request #208
Opened 2020-08-13 19:47 UTC by JSantarelli

Una plex-card es una envolvente rectangular que aloja otros micro-componentes tales como: plex-badge, plex-label, plex-button (y sus respectivos atributos).

- Funcionar como botones destacados en una interfaz (Por ejemplo en puntos de Inicio)

- Representar opciones seleccionables (Usuarios, organizaciones, items propios de un módulo)

- Enriquecer las celdas de una grilla (Por este motivo se combina con el componente plex-grid)

- Definir bloques de información destacada (Recomendable la tipología "invert")

![plex-card-2](https://user-images.githubusercontent.com/5895886/90179916-99901680-dd84-11ea-935f-686a9f2cb7a9.PNG)

2020-08-26 18:21 UTC, andrrrl commented
Bienvenidos al unboxing de `<plex-card>`! :partying_face: 
+ Excelente iniciativa, una herramienta fundamental
+ Muy buenos ejemplos prácticos en la demo

Ahora bien, se detectaron algunos detalles a saber:
1. Contraste badges vs background (en especial warning e info sobre bg success):
![image](https://user-images.githubusercontent.com/11394455/91340427-6602b280-e7ae-11ea-902e-65504a384a0a.png).
Un criterio probable (matetime?) es si hay bg con type, usar badges blancos, misma lógica que con "invert"
2. Algunos card panels son seleccionables, pero no hay feedback visual (cursor de "la manito" :point_up_2:). Quizá no era la idea que sean seleccionables?
3. La card "invert" no invierte su texto al seleccionarse: 
![plex-card-2020-08-26_15 14 14](https://user-images.githubusercontent.com/11394455/91340898-1bce0100-e7af-11ea-99e8-5ccb749378dd.gif)
4. Se podría ver más adelante si pueden fluir o acomodarse al espacio de alguna manera, ya que en resoluciones chicas se pierde en un overflow:
![image](https://user-images.githubusercontent.com/11394455/91341186-8717d300-e7af-11ea-813a-c7dd7423aad1.png)

2020-08-27 11:38 UTC, JSantarelli commented
Muchas gracias @andrrrl ! Buena devolución! Trabajaré en las observaciones. La del punto 4 la idea es que se resuelva con plex-grid como todo lo que sea organización de elementos en el espacio (en la demo está seteado en type="full" y debería estar en type="auto" para que no se comporte como en la captura).

2020-09-04 13:50 UTC, liquid36 requested changes
En definitiva por cada `bg-` debería quedar mas simple:

```
> div.bg-success {
        --color-baseLight: #c7e79c;
        --color-base: #8cc63f;
        --color-tipo: white;
        --color-baseDark: #70a728;
        --color-baseDarker: #55801e;
       @include overButton;
}
```

2020-09-04 13:50 UTC, liquid36 commented on src/lib/css/plex-card.scss
> +    > div:hover {
Haría referencia mediante una clase y no una tag. Como paso con las tabs, si querés cambiar a futuro de div a section (u otro elemento) no necesitas cambiar CSS.

```suggestion
    > .card:hover {
```

2020-09-04 13:50 UTC, liquid36 commented on src/lib/css/plex-card.scss
> +                @include cardBasic;
Este include se repite en todos los tipos de `bg-`, directamente podría ir arriba de todo.

2020-09-04 13:50 UTC, liquid36 commented on src/lib/card/card.component.ts
> +    <div class="card d-flex p-4 bg-{{ type }}" [ngClass]="{'text-white' : type != 'default'}" [class.selected]="selected">
Al tener una clase especifica el d-flex y p-4 se podría llevar directamente al CSS.

2020-09-04 13:50 UTC, liquid36 commented on src/lib/css/plex-card.scss
> +    @mixin overButton{
Movelo arriba de todo, visualmente esta en el medio jaja

2020-09-04 13:50 UTC, liquid36 commented on src/lib/css/plex-card.scss
> +    @mixin overButton{
Además podría incluir todo el CSS que se aplica: 

```
    color: var(--color-base)!important;
    &:hover {
         background: var(--color-baseLight)!important;
    }
```

Esas propiedades se repiten tal cual, cada vez que usas el @include overButton.

Custom properties hace la magía de cambiar de color.

2020-09-04 13:50 UTC, liquid36 commented on src/lib/css/plex-card.scss
> +            }
```
            &:hover {
                @include cardBasic;
                    --color-baseDark: #b9311f;
                    --color-baseDarker: #a12514;
            }
            
            &.selected {
                @include cardBasic;
                --color-baseDark: #b9311f;
                --color-baseDarker: #a12514;
            }
```

Por lo que veo tanto en hover y selected usas el mismo color para --color-baseDark y --color-baseDarker,  Se podría sacar todo eso y definir directamente la variable cuando definis las comunes:

```
--color-baseLight: #ffb3a9;
--color-base: #dd4b39;
--color-tipo: white;
--color-baseDark: #b9311f;
--color-baseDarker: #a12514;
```

Así para cada color.

2020-09-04 13:50 UTC, liquid36 commented on src/lib/css/plex-card.scss
> +        plex-badge > span.badge {
Esto tambien aparece constantemente cada vez que le cambias el background color a la card. Podría quedar todo en el mixins overButton que debería llamarse de otra formar...

cardBackground

2020-09-08 11:00 UTC, liquid36 approved these changes
Excelente!!!! :clap: :clap: :clap:
Muy simple y facil de leer

2020-09-08 15:21 UTC, JSantarelli commented
> Excelente!!!! 👏 👏 👏
> Muy simple y facil de leer

Sep, y una baja en la cantidad de líneas interesante. Gracias Marian!

![lines](https://user-images.githubusercontent.com/5895886/92495750-ad853780-f1cd-11ea-85fa-7054fc0fa896.png)

2020-09-11 14:13 UTC, liquid36 approved these changes

2020-09-11 15:12 UTC, merged

2020-09-11 15:53 UTC, liquid36 commented
:tada: This PR is included in version 6.16.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@andes/plex/v/6.16.0)
- [GitHub release](https://github.com/andes/plex/releases/tag/v6.16.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: