feat(plex-layout): sidebar expansible/contraible
andes/plex pull request #232
Opened 2020-09-26 14:26 UTC by JSantarelli

- Es un atributo que permite desplegar o replegar el sidebar según su necesidad de uso.
- Permite al usuario realizar operaciones de carga y edición en un espacio variable (antiguamente estático y reducido).
- Se implementa mediante el atributo [resizable]="true".
- Toma como valor máximo 6 de las 12 columnas que componen el layout (pantalla partida).
- Se acciona mediate eventos de click o dragueo.

![sidebar-expandible](https://user-images.githubusercontent.com/5895886/94342796-ee60b700-ffe9-11ea-9c5e-ad993b9bc995.gif)

2020-10-06 18:13 UTC, andrrrl commented
La rebaseás y sale!

2020-10-07 15:10 UTC, andrrrl requested changes

2020-10-07 15:16 UTC, JSantarelli commented on src/lib/layout/layout.component.ts
> +                <span class="resizable-btn-wrapper" [class.resizable]="resizable === 'true'" draggable="true">
- Ah bien, gracias andrews...corrijo

- Está el evento dragover aplicado al plex-button que extiende/contrae

2020-10-07 16:55 UTC, andrrrl commented on src/lib/layout/layout.component.ts
> +    public contraer() {
Me parece que la funcionalidad de contraer y expandir debería ser configurable, quizá por pasos con mínimos y máximos:
_el sidebar se contrae/expande entre 4 y 6 columnas, pasando de 2 en 2, algo como:_
`<plex-layout resizable="true" min="4" max="6" step="2">`
Si te parece lo podemos analizar.

2020-10-07 16:58 UTC, andrrrl commented
@JSantarelli está genial la funcionalidad, me parece que le falta un toque para que sea más configurable, te parece que lo sigamos viendo en plex-lab? jaja

2020-10-07 19:27 UTC, JSantarelli commented on src/lib/layout/layout.component.ts
> +    public contraer() {
Buenísimo, Podemos hacer unas pruebas para una primera versión con esos parámetros y una vez implementado monitorear su uso.

2020-10-08 12:45 UTC, liquid36 reviewed
En primera instancia haría que fuese opcional. Les va a aparecer de prepo a todo el mundo.

2020-10-08 12:45 UTC, liquid36 commented on src/lib/layout/layout.component.ts
> +    private valorInicial = new BehaviorSubject<number>(4);
Esta variable no se usa para nada.

2020-10-08 12:45 UTC, liquid36 commented on src/lib/layout/layout.component.ts
> +                <span class="resizable-btn-wrapper" [class.resizable]="resizable === 'true'" draggable="true">
Agregaría un *ngIf  para que no siquieran existan los botonees si no resizable

2020-10-08 12:45 UTC, liquid36 commented on src/lib/layout/layout.component.ts
> +    @Output() calcSidebar = new EventEmitter<number>();
Llammarlo de otra forma, resized.

2020-10-09 12:06 UTC, JSantarelli commented
> En primera instancia haría que fuese opcional. Les va a aparecer de prepo a todo el mundo.

Gracias marian por las observaciones. En este punto, por defecto el recurso está en 'false'. Sólo se activará en las pantallas que consideremos necesaria la expansión del sidebar.

2020-10-09 12:14 UTC, liquid36 commented
> > En primera instancia haría que fuese opcional. Les va a aparecer de prepo a todo el mundo.
> 
> Gracias marian por las observaciones. En este punto, por defecto el recurso está en 'false'. Sólo se activará en las pantallas que consideremos necesaria la expansión del sidebar.

Ese comentario se me olvido borrarlo. Después lo vi. :+1:

2020-10-16 17:05 UTC, andrrrl approved these changes

2020-11-04 17:57 UTC, closed without merging