case directive
andes/plex pull request #234
Opened 2020-10-02 19:08 UTC by andrrrl

- feat(case): agrega directiva case
- feat(case): agrega demo directiva case

2020-10-05 15:22 UTC, JSantarelli requested changes
Se aplicó a diferentes componentes y funciona. Un cambio ínfimo: la directiva tiene un .scss vacío. Se podría borrar si no se utiliza.

2020-10-06 11:52 UTC, andrrrl commented
> Se aplicó a diferentes componentes y funciona. Un cambio ínfimo: la directiva tiene un .scss vacío. Se podría borrar si no se utiliza.

Ah si, es cierto, gracias!

2020-10-06 18:56 UTC, JSantarelli approved these changes
Perfecto!

2020-10-28 18:21 UTC, liquid36 requested changes
capitalize-first: difiere la explicación del caso práctico. La palabra "TEXTO" no se pone en lowercase. 

si arman demo es para agregarle test.

2020-11-05 17:13 UTC, andrrrl commented
> capitalize-first: difiere la explicación del caso práctico. La palabra "TEXTO" no se pone en lowercase.
> 
> si arman demo es para agregarle test.

@liquid36 ahí estuve revisando lo que decías, y en realidad es correcto el funcionamiento actual, quizá haya que reforzar la documentación. Va la aclaración:
Supongamos un texto "ver registros en la HUDS"
- _capitalize_ debería devolver "Ver Registros En La HUDS" y no "Ver Registros En La Huds"
- _capitalize-first_ de manera similar, debería devolver "Ver registros en la HUDS" y no "Ver registros en la huds"
Decime si te queda alguna duda con eso, si se me escapó algo.
@JSantarelli podés aportar también!

2020-11-05 17:47 UTC, andrrrl commented
[Estoy trabajando en los tests así que aun no está para aprobar]

2020-11-06 11:50 UTC, JSantarelli commented
Lo que quizás confunde en el ejemplo de 'capitalize-first' es que el texto de prueba tiene una mayúscula en el medio ("este es Un TEXTO de prueba"). No sé si el resultado esperado sería "Este es un texto de prueba"?. 
![case](https://user-images.githubusercontent.com/5895886/98362979-fb22f280-200c-11eb-9cde-783e8bce415c.JPG)

2020-11-06 12:16 UTC, andrrrl commented
> Lo que quizás confunde en el ejemplo de 'capitalize-first' es que el texto de prueba tiene una mayúscula en el medio ("este es Un TEXTO de prueba"). No sé si el resultado esperado sería "Este es un texto de prueba"?.
> ![case](https://user-images.githubusercontent.com/5895886/98362979-fb22f280-200c-11eb-9cde-783e8bce415c.JPG)

Buenas! el criterio es:
- lowercase/uppercase: pone todo en lowercase/uppercase (buscan corregir el case)
- capitalize: pone todas las primeras letras en mayúscula (busca formatear un texto)
- capitaliza-first: pone la primera letra de la frase en mayúscula (busca fomatear un texto)

La justificación está basada en casos de uso:
- "consulta de enfermería" :arrow_right: **capitalize** :arrow_right: "Consulta De Enfermería"
- "usted está viendo la HUDS de NICO SANTARELLI" :arrow_right: **capitalize-first** :arrow_right: "Usted está viendo la HUDS de NICO SANTARELLI" (sólo cambia la primera "u")

2020-11-06 12:40 UTC, JSantarelli approved these changes
ja.. estas a 10 milímetros de explicar la directiva con dos marcadores?... Se entendió perfecto Andrews, mi duda era si el capitalize-first implicaba que el resto de la frase quede en lowercase; ahora entiendo que no. De éste modo se comporta de la manera esperada. Approved!

2020-11-11 12:01 UTC, liquid36 commented
Yo lo comparaba con el ejemplo y no coincidía. por eso me llamó la atención,

2020-11-11 17:33 UTC, liquid36 requested changes

2020-11-11 17:33 UTC, liquid36 commented on cypress/integration/directiva-case.js
> +            expect(capitalizeTest(text.trim())).equal(capitalizeTest('este es Un TEXTO de prueba'))
Aca y en los otros casos no se esta testeando nada. si los dos textos pasan por la función que capitaliza.

2020-11-11 17:36 UTC, andrrrl commented on cypress/integration/directiva-case.js
> +            expect(capitalizeTest(text.trim())).equal(capitalizeTest('este es Un TEXTO de prueba'))
Si, está sin terminar porque quería ver otra rama y no quería hacer stash así que lo subí así. Te aviso cuando estén los tests listos (ya les encontré solución!)

2020-11-12 14:25 UTC, liquid36 approved these changes

2020-11-13 11:40 UTC, merged

2020-11-17 10:05 UTC, liquid36 commented
:tada: This PR is included in version 7.5.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@andes/plex/v/7.5.0)
- [GitHub release](https://github.com/andes/plex/releases/tag/v7.5.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: