Plex 162
andes/plex pull request #238
Opened 2020-10-28 15:07 UTC by JSantarelli

Dotar al componente de la capacidad de detectar y notificar cuando un filtro oculto está activo.

- Se agrega una función que detecta si los select tienen información.
- Se incorpora un plex-hint que responde al valor que devuelve la función.

![wrapper-hint](https://user-images.githubusercontent.com/5895886/97454933-0fccff80-1916-11eb-971e-5f63346e3c19.gif)

2020-10-28 18:13 UTC, liquid36 requested changes

2020-10-28 18:13 UTC, liquid36 commented on src/lib/wrapper/wrapper.component.ts
> +        <div (mouseover)="hasFilled()">
porque on mouseover?

2020-10-28 18:13 UTC, liquid36 commented on src/lib/wrapper/wrapper.component.ts
> +        this.filled = !!this.elRef.nativeElement.querySelector('section [collapse] div.full');
Ojo porque es re especifico para el plex-select! Plex-wrapper no sabe nada del contenido así que tiene que proveer un palo (interfaz) para que otro pueda indicar que hay datos extras. 

El hint debería mostrarse si es true esta variable y esta oculto los extras.

2020-10-28 18:20 UTC, JSantarelli commented on src/lib/wrapper/wrapper.component.ts
> +        this.filled = !!this.elRef.nativeElement.querySelector('section [collapse] div.full');
Bien, gracias marian! necesitaba una guía... la decisión del mouseover fue porque era el único evento que me permitía disparar la función sin que el usuario deba clickear. Pero entiendo que se debería resolver de otro modo.

2020-12-02 16:38 UTC, liquid36 approved these changes

2020-12-03 16:30 UTC, merged

2020-12-03 18:16 UTC, liquid36 commented
:tada: This PR is included in version 7.9.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@andes/plex/v/7.9.0)
- [GitHub release](https://github.com/andes/plex/releases/tag/v7.9.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: