feat(plex-layout): permite expandir/contraer el sidebar
andes/plex pull request #245
Opened 2020-11-04 17:59 UTC by JSantarelli

- Es un atributo que permite desplegar o replegar el sidebar según su necesidad de uso, permitiendo al usuario realizar operaciones de carga y edición en un espacio flexible (antiguamente estático y reducido).
- Se implementa mediante el selector [resizable]=true y presenta atributos que delimitan y secuencian su expansión: [min], [max] y [steps].
- Toma como valor máximo 10 y mínimo 2 de las 12 columnas que componen el layout.
- Los pasos intermedios pueden setearse en 0 | 1 | 2 | 3 tomando como valor por defecto '0'.
- Se acciona mediate eventos de click o dragueo.

![sidebar-expandible](https://user-images.githubusercontent.com/5895886/98151003-470b5580-1eae-11eb-9aa1-2e5192bda4ad.gif)

2020-11-04 18:53 UTC, andrrrl requested changes

2020-11-04 18:53 UTC, andrrrl commented on src/lib/layout/layout.component.ts
> +        steps = this.steps;
Creo que esto quedó de la otra revisión, es al revés la asignación o no va directamente?
```suggestion
        this.steps = steps;
```

2020-11-04 19:17 UTC, JSantarelli commented on src/lib/layout/layout.component.ts
> +        steps = this.steps;
No iba directamente. Ahi lo corregí. Gracias @andrrrl

2020-11-05 11:18 UTC, andrrrl approved these changes
vamooo!

2020-11-05 11:25 UTC, merged

2020-11-12 12:58 UTC, liquid36 commented
:tada: This PR is included in version 7.4.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@andes/plex/v/7.4.0)
- [GitHub release](https://github.com/andes/plex/releases/tag/v7.4.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: