feat(plex-table): filtros
andes/plex pull request #282
Opened 2021-05-07 12:09 UTC by liquid36

Agrega recurso de filtrado a plex-table

2021-05-11 18:29 UTC, JSantarelli requested changes
Detalles ópticos simplemente. En los headings de las plex-list, los paddings del primer y último elemento (para que quede alineado con la info de los items), y la justificación (flex-end) en el último heading para que quede marginado al final y no al principio de la celda que lo contiene, **sólo cuando hay badge o botones**

Ahora
![actual](https://user-images.githubusercontent.com/5895886/117866490-953e4e80-b26d-11eb-91ae-55f51165e32f.PNG)

Ideal
![margins-justify](https://user-images.githubusercontent.com/5895886/117866517-9bccc600-b26d-11eb-9b30-0da0d5f63515.jpg)

2021-05-11 18:41 UTC, andrrrl commented
> Detalles ópticos simplemente. En los headings de las plex-list, los paddings del primer y último elemento (para que quede alineado con la info de los items), y la justificación (flex-end) en el último heading para que quede marginado al final y no al principio de la celda que lo contiene, **sólo cuando hay badge o botones**
> 
> Ahora
> ![actual](https://user-images.githubusercontent.com/5895886/117866490-953e4e80-b26d-11eb-91ae-55f51165e32f.PNG)
> 
> Ideal
> ![margins-justify](https://user-images.githubusercontent.com/5895886/117866517-9bccc600-b26d-11eb-9b30-0da0d5f63515.jpg)

Se creó [una user](https://proyectos.andes.gob.ar/browse/PLEX-269) para revisar ese tema, gracias!!

2021-05-12 12:25 UTC, JSantarelli approved these changes

2021-05-12 12:31 UTC, merged

2021-05-12 13:05 UTC, liquid36 commented
:tada: This PR is included in version 7.17.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@andes/plex/v/7.17.0)
- [GitHub release](https://github.com/andes/plex/releases/tag/v7.17.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: