plex-tabs: agrega atributos de accesibilidad
andes/plex pull request #285
Opened 2021-05-17 15:41 UTC by JSantarelli

**1. Se agregan roles correspondientes**
⦁ `role="tablist"` al contenedor de las tabs (otorga semántica al elemento, detectando la cantidad de pestañas)
⦁ `role="tab"` al elementos tabeable de la pestaña (identifica al `<li>` como pestaña)
⦁ `role="presentation"` para que el screen reader ignore la semantica de la `<ul>` (que no diga lista, que diga lista de pestañas)

**2. Se agregan arias correspondientes**
⦁ aria-selected _(screen reader menciona la pestaña activa)_
⦁ aria-label _(screen reader menciona descripción del título y botones "cerrar")_

**3. Se agrega funcionalidad accesible por teclado**
⦁ focusable con tab
⦁ navegación con arrows _(flechitas)_
 
**Plus:** se agrega test de cypress al componente

**Para testear:** 
Tabear hasta llegar a las tabs y navegarlas mediante flechas. 
El orden de navegación debería ser: tab-header > tab-body > siguiente tab-header > siguiente tab-body (salvo casos con botoneras)

![Plex-Tabs](https://user-images.githubusercontent.com/5895886/118516933-29486400-b70d-11eb-878b-74dabc49383e.gif)

2021-05-18 11:15 UTC, liquid36 requested changes
Revisar el comentario en todo lo demás

2021-05-18 11:15 UTC, liquid36 commented on src/lib/tabs/tabs.component.ts
> +                        <a tabindex="{{ tab.active ? '0' : '-1' }}" role="tab" attr.aria-selected="{{ tab.active }}" attr.aria-label="{{ tab.label }}" id="{{ tab.label }}" class="nav-link" [ngClass]=
Recomiendo usar los bindings de angular:

```suggestion
                        <a [attr.tabindex]="tab.active ? '0' : '-1'" role="tab" [attr.aria-selected]="tab.active" [attr.aria-label]=" tab.label" [attr.id]="tab.label" class="nav-link" [ngClass]="{active: tab.active}" plexRipples onclick="return false">
```

Ojo con mezclar las cosas: Acá va un ejemplo : https://angular.io/guide/accessibility#accessibility-attributes

2021-05-18 11:22 UTC, JSantarelli commented on src/lib/tabs/tabs.component.ts
> +                        <a tabindex="{{ tab.active ? '0' : '-1' }}" role="tab" attr.aria-selected="{{ tab.active }}" attr.aria-label="{{ tab.label }}" id="{{ tab.label }}" class="nav-link" [ngClass]=
Gracias @liquid36

2021-06-04 11:53 UTC, sychus approved these changes

2021-07-06 18:35 UTC, andrrrl approved these changes
Se ve bien!

2021-07-12 17:47 UTC, liquid36 approved these changes

2021-07-12 17:48 UTC, merged

2021-07-19 15:15 UTC, liquid36 commented
:tada: This PR is included in version 7.18.2 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@andes/plex/v/7.18.2)
- [GitHub release](https://github.com/andes/plex/releases/tag/v7.18.2)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: