PLEX-BOOL - Reveer Diseño
andes/plex pull request #313
Opened 2022-04-05 13:10 UTC by palita1991

https://proyectos.andes.gob.ar/browse/PLEX-169

2022-04-20 15:10 UTC, martinebucarey requested changes
Al probarlo en algunos componentes de la app el bool queda escondido
https://www.loom.com/share/765b16c488bc44c6a5d63e6c9c9a6230

2022-04-21 15:06 UTC, palita1991 commented
> Al probarlo en algunos componentes de la app el bool queda escondido https://www.loom.com/share/765b16c488bc44c6a5d63e6c9c9a6230

@martinebucarey Resuelto

2022-07-01 17:37 UTC, martinebucarey commented
> > Al probarlo en algunos componentes de la app el bool queda escondido https://www.loom.com/share/765b16c488bc44c6a5d63e6c9c9a6230
> 
> @martinebucarey Resuelto

ahora si, una beleza

2022-07-05 14:42 UTC, merged

2022-07-05 17:09 UTC, liquid36 commented
:tada: This PR is included in version 7.23.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@andes/plex/v/7.23.0)
- [GitHub release](https://github.com/andes/plex/releases/tag/v7.23.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: