PLEX-BADGE -  Tipología multilinea
andes/plex pull request #315
Opened 2022-04-06 18:11 UTC by palita1991

https://proyectos.andes.gob.ar/browse/PLEX-229

2022-04-12 17:21 UTC, AgosLizzi approved these changes

2022-04-20 15:33 UTC, martinebucarey requested changes
Cuando el badge esta solo queda perfecto y salva la parte que se rompe 
![imagen](https://user-images.githubusercontent.com/56874534/164267758-3f9555d1-43da-4c12-9019-ca01d64dbacd.png)
Cuando tiene un botón adentro, el botón sigue quedando chico, por ahí habría que tratar de que si se agranda el badge se agrande el botón.
![imagen](https://user-images.githubusercontent.com/56874534/164268000-ddc76c0c-4605-4443-b572-3aac991f1282.png)

2022-04-20 18:38 UTC, palita1991 commented
> Cuando el badge esta solo queda perfecto y salva la parte que se rompe ![imagen](https://user-images.githubusercontent.com/56874534/164267758-3f9555d1-43da-4c12-9019-ca01d64dbacd.png) Cuando tiene un botón adentro, el botón sigue quedando chico, por ahí habría que tratar de que si se agranda el badge se agrande el botón. ![imagen](https://user-images.githubusercontent.com/56874534/164268000-ddc76c0c-4605-4443-b572-3aac991f1282.png)

@martinebucarey ahi se arregló cuando el badge tiene un boton adentro. Ahora el botón toma la altura que posee el badge asi quedan alineados.

2022-07-05 13:40 UTC, martinebucarey approved these changes

2022-07-05 15:52 UTC, merged

2022-07-05 17:09 UTC, liquid36 commented
:tada: This PR is included in version 7.23.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@andes/plex/v/7.23.0)
- [GitHub release](https://github.com/andes/plex/releases/tag/v7.23.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: